"""Instruction data: load, dedup, length-filter, and persist disjoint train/eval/calib splits.

Only the instruction (+ optional input) fields are used — responses are generated by the
executor, never taken from the dataset.
"""
import json
import os
import random


def _instruction_text(ex):
    instr = (ex.get("instruction") or "").strip()
    inp = (ex.get("input") or "").strip()
    if inp:
        return f"{instr}\n\n{inp}"
    return instr


def build_or_load_splits(cfg, tokenizer):
    """Return dict with 'train', 'eval', 'calib' lists of instruction strings.

    Splits are persisted to cfg.data.split_path and reused (fixed seed) on later runs.
    """
    path = cfg.data.split_path
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)

    from datasets import load_dataset
    ds = load_dataset(cfg.data.dataset, split="train")

    seen, items = set(), []
    max_tok = cfg.data.max_prompt_tokens
    for ex in ds:
        text = _instruction_text(ex)
        if not text or text in seen:
            continue
        if len(tokenizer(text, add_special_tokens=False).input_ids) > max_tok:
            continue
        seen.add(text)
        items.append(text)

    rng = random.Random(cfg.seed)
    rng.shuffle(items)

    n_tr, n_ev, n_ca = cfg.data.n_train, cfg.data.n_eval, cfg.data.n_calib
    need = n_tr + n_ev + n_ca
    if len(items) < need:
        raise ValueError(f"dataset has {len(items)} usable items, need {need}")
    splits = {
        "train": items[:n_tr],
        "eval": items[n_tr:n_tr + n_ev],
        "calib": items[n_tr + n_ev:n_tr + n_ev + n_ca],
    }
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        json.dump(splits, f)
    return splits
