"""Plan head + codebook. Three modes behind one interface (config `plan.plan_mode`):

  gumbel_codebook : trainable codebook C[K,d]; plan slot p_i = sum_k alpha_ik C_k,
                    alpha = gumbel_softmax(logits_i, tau). fp32 at low tau.
  vq_codebook     : encoder emits z_i; quantize to nearest code e_i; straight-through
                    p_i = z_i + sg(e_i - z_i); commitment loss; EMA codebook + dead-code reinit.
  hard_text       : planner generates a natural-language plan; REINFORCE on its token
                    log-probs. Plan vectors are the embeddings of the generated tokens.

The planner backbone (LoRA) ENCODES the instruction; this module owns only the new
trainable parameters (plan head + gumbel codebook) so the optimizer can target them
separately from the LoRA params.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


class PlanGenerator(nn.Module):
    def __init__(self, bundle, cfg):
        super().__init__()
        # Keep `bundle` OUT of the module tree so its (LoRA) params are not double-counted
        # by PlanGenerator.parameters().
        object.__setattr__(self, "bundle", bundle)
        self.cfg = cfg
        self.mode = cfg.plan.plan_mode
        self.N = int(cfg.plan.N)
        self.K = int(cfg.plan.K)
        self.d = int(cfg.plan.d_code) if cfg.plan.d_code else bundle.hidden_size
        d_model = bundle.hidden_size

        if self.mode == "gumbel_codebook":
            self.proj = nn.Linear(d_model, self.N * self.K)
            self.codebook = nn.Parameter(torch.randn(self.K, self.d) / (self.d ** 0.5))
        elif self.mode == "vq_codebook":
            self.proj = nn.Linear(d_model, self.N * self.d)
            self.register_buffer("codebook", torch.randn(self.K, self.d) / (self.d ** 0.5))
            # EMA accumulators + usage tracking for dead-code reinit.
            self.register_buffer("ema_cluster_size", torch.zeros(self.K))
            self.register_buffer("ema_w", self.codebook.clone())
            self.register_buffer("steps_since_used", torch.zeros(self.K))
        elif self.mode == "hard_text":
            # No new params: plan is natural-language text generated by the planner itself.
            pass
        else:
            raise ValueError(f"unknown plan_mode {self.mode}")

        self.to(bundle.device)
        if self.mode in ("gumbel_codebook", "vq_codebook"):
            self.proj.to(bundle.dtype)

    # ---- instruction encoding --------------------------------------------
    def encode(self, instructions):
        """Run the planner backbone over the instruction; pool the last token's hidden state."""
        tok = self.bundle.tokenizer
        texts = [f"<|im_start|>user\n{x}<|im_end|>" for x in instructions]
        enc = tok(texts, return_tensors="pt", padding=True, add_special_tokens=False)
        enc = {k: v.to(self.bundle.device) for k, v in enc.items()}
        out = self.bundle.planner_forward(
            input_ids=enc["input_ids"], attention_mask=enc["attention_mask"],
            output_hidden_states=True,
        )
        # Left padding -> the real last token is at index -1 for every row.
        h = out.hidden_states[-1][:, -1, :]
        return h  # [M, d_model]

    # ---- gumbel noise (kept fixed between generation and the grad pass) ---
    def sample_gumbel(self, m):
        u = torch.rand(m, self.N, self.K, device=self.bundle.device).clamp_(1e-9, 1 - 1e-9)
        return -torch.log(-torch.log(u))

    # ---- main interface ---------------------------------------------------
    def compute_plans(self, instructions, noise=None, tau=1.0, hard=False):
        """Return (plan_vectors [M, N, d], aux). Differentiable in the planner params.

        For gumbel mode, pass the SAME `noise` used at generation time so the grad
        pass reconstructs the exact plan that produced the sampled response.
        """
        if self.mode == "hard_text":
            raise RuntimeError("hard_text uses generate_text_plan(), not compute_plans()")

        h = self.encode(instructions)
        m = h.shape[0]

        if self.mode == "gumbel_codebook":
            logits = self.proj(h).view(m, self.N, self.K).float()  # fp32 (bf16 underflows at low tau)
            if hard:
                idx = logits.argmax(-1)
                alpha = F.one_hot(idx, self.K).float()
            else:
                if noise is None:
                    noise = self.sample_gumbel(m)
                alpha = F.softmax((logits + noise) / tau, dim=-1)
            p = alpha @ self.codebook.float()              # [M, N, d]
            p = p.to(self.bundle.dtype)
            with torch.no_grad():
                peak = alpha.max(-1).values.mean().item()
            aux = {
                "logits": logits, "alpha": alpha, "indices": alpha.argmax(-1),
                "peakedness": peak, "tau": tau, "commit_loss": None,
            }
            return p, aux

        # vq_codebook
        z = self.proj(h).view(m, self.N, self.d).float()       # [M, N, d]
        flat = z.reshape(-1, self.d)                            # [M*N, d]
        cb = self.codebook.float()
        dist = torch.cdist(flat, cb)                           # [M*N, K]
        idx = dist.argmin(-1)                                  # [M*N]
        e = cb[idx].view(m, self.N, self.d)
        idx2 = idx.view(m, self.N)
        p = z + (e - z).detach()                              # straight-through
        p = p.to(self.bundle.dtype)
        commit = self.cfg.plan.vq.beta * F.mse_loss(z, e.detach())
        with torch.no_grad():
            onehot = F.one_hot(idx, self.K).float()
            probs = onehot.mean(0)
            perplexity = torch.exp(-(probs * (probs + 1e-10).log()).sum()).item()
        aux = {
            "z": z, "e": e, "indices": idx2, "commit_loss": commit,
            "perplexity": perplexity, "usage": int((onehot.sum(0) > 0).sum().item()),
        }
        return p, aux

    # ---- VQ codebook maintenance (call once per step, no grad) ------------
    @torch.no_grad()
    def vq_update(self, aux):
        if self.mode != "vq_codebook" or not self.cfg.plan.vq.ema:
            return
        z = aux["z"].detach().reshape(-1, self.d).float()
        idx = aux["indices"].reshape(-1)
        onehot = F.one_hot(idx, self.K).float()               # [M*N, K]
        decay = self.cfg.plan.vq.ema_decay
        cluster = onehot.sum(0)
        self.ema_cluster_size.mul_(decay).add_(cluster, alpha=1 - decay)
        dw = onehot.t() @ z                                   # [K, d]
        self.ema_w.mul_(decay).add_(dw, alpha=1 - decay)
        n = self.ema_cluster_size.sum()
        weights = (self.ema_cluster_size + 1e-5) / (n + self.K * 1e-5) * n
        self.codebook.copy_(self.ema_w / weights.unsqueeze(1))

        used = cluster > 0
        self.steps_since_used[used] = 0
        self.steps_since_used[~used] += 1
        dead = self.steps_since_used >= self.cfg.plan.vq.dead_code_steps
        if dead.any():
            # Reseed dead codes from recent encoder outputs (codebook collapse made visible).
            n_dead = int(dead.sum().item())
            src = z[torch.randint(0, z.shape[0], (n_dead,), device=z.device)]
            self.codebook[dead] = src
            self.ema_w[dead] = src
            self.ema_cluster_size[dead] = 1.0
            self.steps_since_used[dead] = 0

    # ---- hard_text baseline ----------------------------------------------
    def generate_text_plan(self, instructions, max_plan_tokens):
        """Generate a NL plan from the planner; return plan token ids per example."""
        tok = self.bundle.tokenizer
        sys = self.cfg.plan.system_prompt
        texts = [
            f"<|im_start|>system\n{sys}<|im_end|>\n<|im_start|>user\n"
            f"Write a brief step-by-step plan to answer: {x}<|im_end|>\n<|im_start|>assistant\n"
            for x in instructions
        ]
        enc = tok(texts, return_tensors="pt", padding=True, add_special_tokens=False)
        enc = {k: v.to(self.bundle.device) for k, v in enc.items()}
        with torch.no_grad():
            gen = self.bundle.planner.generate(
                **enc, max_new_tokens=max_plan_tokens, do_sample=True, temperature=1.0,
                pad_token_id=tok.pad_token_id, eos_token_id=tok.eos_token_id,
            )
        new = gen[:, enc["input_ids"].shape[1]:]
        plans = []
        for row in new:
            ids = row.tolist()
            if tok.eos_token_id in ids:
                ids = ids[: ids.index(tok.eos_token_id)]
            plans.append([t for t in ids if t != tok.pad_token_id] or [tok.eos_token_id])
        return plans

    def plan_token_logprobs(self, instructions, plan_ids_list):
        """Teacher-force generated plan tokens through the planner -> mean log-prob (REINFORCE)."""
        tok = self.bundle.tokenizer
        sys = self.cfg.plan.system_prompt
        outs = []
        for x, plan_ids in zip(instructions, plan_ids_list):
            prompt = tok(
                f"<|im_start|>system\n{sys}<|im_end|>\n<|im_start|>user\n"
                f"Write a brief step-by-step plan to answer: {x}<|im_end|>\n<|im_start|>assistant\n",
                add_special_tokens=False,
            ).input_ids
            full = torch.tensor(prompt + plan_ids, device=self.bundle.device)[None]
            logits = self.bundle.planner_forward(input_ids=full).logits[0]
            lp = prompt.__len__()
            tgt = torch.tensor(plan_ids, device=self.bundle.device)
            logp = F.log_softmax(logits[lp - 1: lp - 1 + len(plan_ids)].float(), -1)
            outs.append(logp[torch.arange(len(plan_ids)), tgt].mean())
        return torch.stack(outs)

    def embed_text_plan(self, plan_ids_list):
        """Embeddings of generated plan tokens, padded to a common N for prefix injection."""
        n = max(len(p) for p in plan_ids_list)
        d = self.bundle.hidden_size
        out = torch.zeros(len(plan_ids_list), n, d, dtype=self.bundle.dtype, device=self.bundle.device)
        for i, ids in enumerate(plan_ids_list):
            out[i, : len(ids)] = self.bundle.embed_tokens(torch.tensor(ids, dtype=torch.long))
        return out
